spring:
  application:
    name: action-eureka-server

server:
  address: 127.0.0.1
  port: 8888

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${server.address}:8888/eureka

